// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package hello

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HelloserviceClient is the client API for Helloservice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloserviceClient interface {
	Hello(ctx context.Context, in *Hellorequest, opts ...grpc.CallOption) (*Helloresponse, error)
}

type helloserviceClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloserviceClient(cc grpc.ClientConnInterface) HelloserviceClient {
	return &helloserviceClient{cc}
}

func (c *helloserviceClient) Hello(ctx context.Context, in *Hellorequest, opts ...grpc.CallOption) (*Helloresponse, error) {
	out := new(Helloresponse)
	err := c.cc.Invoke(ctx, "/hello.helloservice/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloserviceServer is the server API for Helloservice service.
// All implementations must embed UnimplementedHelloserviceServer
// for forward compatibility
type HelloserviceServer interface {
	Hello(context.Context, *Hellorequest) (*Helloresponse, error)
	mustEmbedUnimplementedHelloserviceServer()
}

// UnimplementedHelloserviceServer must be embedded to have forward compatible implementations.
type UnimplementedHelloserviceServer struct {
}

func (UnimplementedHelloserviceServer) Hello(context.Context, *Hellorequest) (*Helloresponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedHelloserviceServer) mustEmbedUnimplementedHelloserviceServer() {}

// UnsafeHelloserviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloserviceServer will
// result in compilation errors.
type UnsafeHelloserviceServer interface {
	mustEmbedUnimplementedHelloserviceServer()
}

func RegisterHelloserviceServer(s grpc.ServiceRegistrar, srv HelloserviceServer) {
	s.RegisterService(&Helloservice_ServiceDesc, srv)
}

func _Helloservice_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Hellorequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloserviceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.helloservice/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloserviceServer).Hello(ctx, req.(*Hellorequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Helloservice_ServiceDesc is the grpc.ServiceDesc for Helloservice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Helloservice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hello.helloservice",
	HandlerType: (*HelloserviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Helloservice_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/hello.proto",
}
